name: Clear all Github actions caches
on:
  workflow_dispatch:

permissions:
  actions: write

jobs:
  clear-cache:
    name: Delete all caches
    runs-on: ubuntu-20.04
    steps:
      - name: Clear caches
        uses: easimon/wipe-cache@5f305e3ee1b681c44328cdf11eaedf943b60edff # main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}